# Cloud Build 設定ファイル
steps:
  # Dockerイメージのビルドとタグ付け
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest', '.']
  
  # ビルドしたイメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest']

# 変数定義
substitutions:
  _REPOSITORY: test-repo
  _IMAGE_NAME: nginx

# ビルドされるイメージ
images:
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'
