# Cloud Build 設定ファイル
steps:
  # Dockerイメージのビルドとタグ付け
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'build', '--platform', 'linux/amd64', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest', '--push', '.']
  
  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', 'nginx-app', '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest', '--region', '${_REGION}']

# 変数定義
substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: test-repo
  _IMAGE_NAME: nginx

# ビルドされるイメージ
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:latest'

# ログの設定
logsBucket: 'gs://${PROJECT_ID}-cloudbuild-logs'
options:
  logging: 'GCS_ONLY'
